/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CardPanel.java
 *
 * Created on Jul 17, 2010, 1:57:24 PM
 */

package com.mm;

import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author MAHBUB
 */
public class CardPanel extends javax.swing.JPanel {

    Icon icon, faceDownIcon;
    Card card;

    boolean visibility;

    public static final int DEFAULT_CARD_WIDTH = 72;
    public static final int DEFAULT_CARD_HEIGHT = 96;
    

    /** Creates new form CardPanel */
    public CardPanel() {
        initComponents();
        Init();

    }

    public CardPanel(Card c, boolean isVisible)
    {
        initComponents();
        Init();
        card = c;
        visibility = isVisible;
        icon = new ImageIcon(getClass().getResource("/resources/" + card.toString() +".png"));
        if(isVisible == true)
            picJLabel.setIcon(icon);
        else picJLabel.setIcon(faceDownIcon);
    }

    private void Init()
    {
        icon = null;
        card = null;

        faceDownIcon = new ImageIcon(getClass().getResource("/resources/cardup.png"));
    }

    public void setCard(Card c, boolean isVisible)
    {
        card = c;
        visibility = isVisible;
        icon = new ImageIcon(getClass().getResource("/resources/" + card.toString() +".png"));
        if(isVisible == true)
            picJLabel.setIcon(icon);
        else picJLabel.setIcon(faceDownIcon);
    }

    public void setFaceDown()
    {
        picJLabel.setIcon(faceDownIcon);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picJLabel = new javax.swing.JLabel();

        picJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cardup.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel picJLabel;
    // End of variables declaration//GEN-END:variables

}
