/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Jul 17, 2010, 1:48:55 PM
 */

package com.mm;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Menu;
import java.awt.MenuBar;
import java.awt.MenuItem;
import java.awt.MenuShortcut;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author MAHBUB
 */
public class MainFrame extends javax.swing.JFrame implements ActionListener {

    MainPanel mainPanel = new MainPanel();

// ---------------------------- Frame Size Variable ----------------------------
    Dimension dim;
    int frameWidth, frameHeight;
// -----------------------------------------------------------------------------

// ------------------------ Menu Variable --------------------------------------
    MenuBar mb;
    Menu gameMenu, helpMenu;
    MenuItem newGameItem, optionItem, scoreItem, exitItem;
    MenuItem helpTopicItem, aboutHeartItem;
// -----------------------------------------------------------------------------
    


    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        InitManuBar();

        dim = Toolkit.getDefaultToolkit().getScreenSize();
        frameWidth = (int) (dim.width * .7) ;
        frameHeight = (int) (dim.height * .8);

        this.setBounds((dim.width - frameWidth)/2, (dim.height - frameHeight)/2 - 20, frameWidth, frameHeight);

        add(mainPanel);
        mainPanel.ResetGame();

        this.setTitle("mHearts v1.0");

//        setSize();
        
//        pack();
    }

    private void InitManuBar()
    {
        mb = new MenuBar();

        gameMenu = new Menu("Game");
        newGameItem = new MenuItem("New Game", new MenuShortcut(KeyEvent.VK_N));
        optionItem = new MenuItem("Option...", new MenuShortcut(KeyEvent.VK_O));
        scoreItem  = new MenuItem("Score", new MenuShortcut(KeyEvent.VK_S));
        exitItem   = new MenuItem("Exit", new MenuShortcut(KeyEvent.VK_E));

        newGameItem.addActionListener(this);
        optionItem.addActionListener(this);
        scoreItem.addActionListener(this);
        exitItem.addActionListener(this);

        gameMenu.add(newGameItem);
//        gameMenu.add(optionItem);
//        gameMenu.add(scoreItem);
        gameMenu.addSeparator();
        gameMenu.add(exitItem);

        mb.add(gameMenu);

        helpMenu = new Menu("Help");
        helpTopicItem = new MenuItem("Help Topic F1", new MenuShortcut(KeyEvent.VK_F1));
        aboutHeartItem = new MenuItem("About");

        helpTopicItem.addActionListener(this);
        aboutHeartItem.addActionListener(this);

        
        helpMenu.add(helpTopicItem);
        helpMenu.add(aboutHeartItem);

        mb.add(helpMenu);

        this.setMenuBar(mb);


    }




    public void actionPerformed(ActionEvent evt)
    {
        if(evt.getSource() == newGameItem)
            mainPanel.NewGameAction();
        else if(evt.getSource() == exitItem)
            System.exit(0);
        else if(evt.getSource() == helpTopicItem)
            mainPanel.HelpTopicAction();
        else if(evt.getSource() == aboutHeartItem)
            mainPanel.AboutHeartAction();
    }






    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        MainFrame frame = new MainFrame();
        frame.setVisible(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
